proxies:
- name: 自动节点-1
  type: http
  server: 4a478ae2-tl4g00-tl4lsp-l2zi.nbg1-dc4.ukuaishou.com
  port: 443
  tls: true
  sni: 4a478ae2-tl4g00-tl4lsp-l2zi.nbg1-dc4.ukuaishou.com
  skip-cert-verify: false
- name: 自动节点-2
  type: http
  server: 106e4cb5-tl4g00-tl4lsp-l2zi.hel1-dc2.ukuaishou.com
  port: 443
  tls: true
  sni: 106e4cb5-tl4g00-tl4lsp-l2zi.hel1-dc2.ukuaishou.com
  skip-cert-verify: false
