proxies:
- name: 自动节点-1
  type: http
  server: 97547538-tla000-tla6gb-l45g.nbg1-dc4-09092006.ukuaishou.com
  port: 443
  tls: true
  sni: 97547538-tla000-tla6gb-l45g.nbg1-dc4-09092006.ukuaishou.com
  skip-cert-verify: false
- name: 自动节点-2
  type: http
  server: 4560ea0b-tla000-tla6gb-l45g.hel1-dc2-09092006.ukuaishou.com
  port: 443
  tls: true
  sni: 4560ea0b-tla000-tla6gb-l45g.hel1-dc2-09092006.ukuaishou.com
  skip-cert-verify: false
